name: GitHub Actions Demo
run-name: For-practice
on:
  workflow_dispatch: 
env:
  IMAGE_NAME: adityavishwakarma31/django-todo-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull image
        run: docker pull ${{env.IMAGE_NAME}}
      - name: list of images
        run: docker images
        
      
