name: GitHub Actions Demo

run-name: For-practice

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Get Version
        run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t myapp:${{ env.VERSION }} .

      - name: List Docker images
        run: docker images
